version: "3.9"

services:
  db_seeder:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./tsconfig.json:/usr/src/app/tsconfig.json:ro
      - ./seeder:/usr/src/app/seeder:ro
    env_file:
      - ./.env
