run-name: Test, build, and deploy the PR to main created by @${{ github.actor }} to staging environment

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy_to_staging:
    name: Deploy build artifact to staging environment
    environment: staging_environment
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Post image ID to PR
        uses: actions/github-script@v7
        with:
          script: |
            console.log('first log: ', process.env.TEST_VAR)
            const imageId = '${{ vars.APP_ENV }}';
            const { data } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The Docker image ID for this build is: ${imageId}`
            });
            core.exportVariable('TEST_VAR', imageId)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          console.log('second log: ', process.env.TEST_VAR)
