run-name: Test, build, and deploy the PR to main created by @${{ github.actor }} to staging environment

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  deploy_to_staging:
    name: Deploy build artifact to staging environment
    environment: staging_environment
    runs-on: ubuntu-22.04
    steps:
      - name: Post image ID to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GHA_PAT }}
          script: |
            const imageId = '${{ vars.APP_ENV }}';
            const varName = context.ref.replaceAll('/', '_').toUpperCase();
            const repoVars = await github.rest.actions.listRepoVariables({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            const commentId = repoVars.data.variables.find(v => v.name === varName)?.value;
            if (commentId) {
              await github.rest.issues.deleteComment({
                comment_id: Number(commentId),
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              const {data} = await github.rest.issues.createComment({
                comment_id: Number(commentId),
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `The Docker image ID for this build is: ${imageId}`
              });
              await github.rest.actions.updateRepoVariable({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: varName,
                value	: data.id.toString()
              });
            } else {
              const { data } = await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `The Docker image ID for this build is: ${imageId}`
              });
              await github.rest.actions.createRepoVariable({
                owner: context.repo.owner,
                repo: context.repo.repo,
                name: varName,
                value	: data.id.toString()
              });
            }
