run-name: Test PR to main created by @${{ github.actor }}

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  run_integ_test:
    name: Run integration test
    strategy:
      matrix:
        # os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
        # version: [18, 20, 22]
        os: [ubuntu-latest]
        version: [18]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Install Dependencies
        run: npm ci
      - name: Run linter tests
        run: npm run lint
      - name: Run integration tests
        run: npm run test
